url: "http://localhost:4000" #"https://dongjaelee95.github.io" # "http://localhost:4000"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dongjae Lee" # the name of your site, e.g. ACME Corp.
last-updated: Oct 12, 2025

include:
  - _posts
  - files
  - img
